### ISSUE TITLE
License of dataset

### ISSUE THREAD

**Issue by Cakem1x** [lifelong-robotic-vision/lifelong-robotic-vision.github.io#22]
Hi everyone,

first of all, thank you very much for publishing this nice dataset and evaluations in your paper!

I'm wondering about the license of the dataset. Does the BSD-4-Clause license also extend to the dataset, or only to the code of the website? This wasn't clear to me.
It's important for me to know under which circumstances I'm allowed to use the dataset (commercially, research-only, etc.).
See e.g. the KITTI License: http://www.cvlibs.net/datasets/kitti/ -> "Copyright" explicitly mentions that this refers to the dataset (and the benchmarks).

Thanks for clarifying!

**Comment by cedrusx** [comment]
Hi Matthias, the datasets are released with the [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/) license.
