### ISSUE TITLE
Remove the title numbering.

### ISSUE THREAD

**Issue by yk-liu** [lifelong-robotic-vision/lifelong-robotic-vision.github.io#7]
Hi, I don't know if you have checked your issue on my repo. I moved that to PointingToTheMoon and closed it.

Anyway, the solution is to add 
numbering: false
to the front matter of the page.

Cheers!

**Comment by cedrusx** [comment]
Hi Yingkai, thanks a lot for helping address our issue. I have tried the solution with our [competition page](https://github.com/lifelong-robotic-vision/lifelong-robotic-vision.github.io/blob/master/competition/index.md), but [the numbers are still there](https://lifelong-robotic-vision.github.io/competition/), sadly. Is there anything I got wrong?

**Comment by yk-liu** [comment]
Hi, I looked into it and it's because your page used the info layout instead of post.
I created a pull request #8 fixing the issue.
After you merge it, it should be fixed. If not, pls let me know.
Sorry for the inconvenience it caused

**Comment by cedrusx** [comment]
Fixed. Many thanks Yingkai for your time and patience!
